services:
  - type: pserv
    name: psql
    region: oregon
    runtime: docker
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: PORT
        value: 80
      - key: OLD_DATABASE_URL
        sync: false
      - key: NEW_DATABASE_URL
        sync: false

databases:
  - name: bounce-data-15
    plan: standard
    postgresMajorVersion: 15
    databaseName: bounce_data